config/routes.rb
EssenceDiamant::Application.routes.draw do
	resources :subscribers
  root to: 'static_pages#home'

  match '/english', to: 'static_pages#english', via: 'get'
  match '/lapproche_diamant', to: 'static_pages#texts_1_lapproche_diamant', via: 'get'
  match '/hameed_lenseignant', to: 'static_pages#texts_2_hameed_lenseignant', via: 'get'
  match '/la_collecte_du_miel', to: 'static_pages#texts_3_la_collecte_du_miel', via: 'get'

  match "/mailchimp", to: 'subscribers#mailchimp_event', via: 'get'

end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
	before_save { self.email = email.downcase }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
										uniqueness: { case_sensitive: false }

	def add_subscriber_to_mailchimp
		gb = Gibbon.new("9a74ef27a5472f7a63e06d6dbe7bba7a-us7")

		group = { :id => gb.list_interest_groupings(:api_key => "9a74ef27a5472f7a63e06d6dbe7bba7a-us7", :id => "450a3cc3cd")[0]["id"] }
		gb.list_subscribe({:id => "450a3cc3cd", :email_address => self.email, :update_existing => true, 
									     :double_optin => false, :send_welcome => false, 
									     :merge_vars => {'GROUPINGS' => {0 => {'id' => group[:id], 'groups' => self.language}}} })
		update_attribute(:active, true)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def english
  end

  def texts_1_lapproche_diamant
  end

  def texts_2_hameed_lenseignant
  end

  def texts_3_la_collecte_du_miel
  end  
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController

	def english_subscribe_success
	end

	def french_subscribe_success
	end

	def english_subscribe_failure
	end

	def french_subscribe_failure
	end

	def create
		@subscriber = Subscriber.new(email: params[:subscriber][:email], language: params[:subscriber][:language], active: false)
		if @subscriber.save
			@subscriber.delay(queue: "add_subscribers", priority: 10).add_subscriber_to_mailchimp
			if params[:subscriber][:language] == "French"
				render 'french_subscribe_success'
		  elsif params[:subscriber][:language] == "English"
		 		render 'english_subscribe_success'
		  end
		else
			if params[:subscriber][:language] == "French"
				render 'french_subscribe_failure'
		  elsif params[:subscriber][:language] == "English"
		 		render 'english_subscribe_failure'
		  end
		end
	end

	def mailchimp_event
		if params[:type] == "unsubscribe"
		  @subscriber = Subscriber.find_by(email: params[:data][:email])
		  @subscriber.destroy
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Returns the full title on a per-page basis.
	def full_title(page_title)
		base_title = "Essence Diamant"
		if page_title.empty?
			base_title
	  else 
	  	"#{base_title} | #{page_title}"
	  end
	end

	# Returns appropriate footer for english or french pages
	def footer(footer)
		french_footer = 'layouts/frenchfooter'
		if footer.empty?
			french_footer
		else 
			footer
		end
	end

	# Returns appropriate quote for english or french pages
	def quote(quote)
		french_quote = '« Les façons vagues, métaphoriques ou poétiques de décrire le processus de renaissance spirituelle ajoutent souvent plus de confusion que de clarté. Elles peuvent avoir un attrait esthétique et nous inspirer, mais pour la personne assoiffée, voire agonisante, une façon raffinée de décrire le chemin qui mène au puits ne vaut pas tant qu’une description précise, claire et succincte. De plus, la précision elle-même radie une esthétique particulière, une beauté claire et lumineuse semblable à la beauté d’un précieux diamant. »'
		if quote.empty?
			french_quote
		else
			quote
		end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/layouts/_englishfooter.html.erb
<footer class="footer">
	<div id="footer-holder">
		<div id="footer-col-holder">
			<div class="footer-col">
				<h3 class="contact-header">Contact</h3>
				<a id="email-button" href="mailto:essencediamant@gmail.com">Email Us</a>
				<address>
					<span>Essence Diamant France</span>
					<span>Laudonie</span>
					<span>24390 Tourtoirac</span>
				</address>
			</div>
			<div class="footer-col">
				<h3 class="subscribe-header">Subscribe</h3>
				<p>
					Receive updates as we realize our goal of bringing Diamond Approach workshops and books to France.
				</p>
				<%= form_for(Subscriber.new) do |f| %>
					<%= f.label "Email:" %>
					<%= f.text_field :email %>
					<%= f.hidden_field :language, :value => "English" %>
					<%= f.submit "Subscribe", class: "button" %>
				<% end %>
			</div>
			<div class="footer-col footer-col-paragraph">
				<h3 class="follow-header">Follow</h3>
				<p>Join the Essence Diamant Facebook Group:</p>
				<a href="https://facebook.com/EssenceDiamantFrance" target="_blank"><%= image_tag image_path('facebook-link.gif')%></a>
			</div>
		</div>
		<div id="copy">
	    <p>
		    Created with Ruby on Rails by
		    <a href="http://joepeloquin.com/" target="_blank">Joe Peloquin</a> 
		    • Text: Kevin Dancelme •
      </p>
      <p>
  	    © 2013 DIAMOND APPROACH, RIDHWAN DIAMOND APPROACH, RIDHWAN, and the Ridhwan "Hu" symbol are registered trademarks of the Ridhwan Foundation.
      </p>
    </div>
  </div>
</footer>

app/views/layouts/_frenchfooter.html.erb
<footer class="footer">
	<div id="footer-holder">
		<div id="footer-col-holder">
			<div class="footer-col">
				<h3 class="contact-header">Contact</h3>
				<a id="email-button" href="mailto:essencediamant@gmail.com">Nous Contacter</a>
				<address>
					<span>Essence Diamant France</span>
					<span>Laudonie</span>
					<span>24390 Tourtoirac</span>
				</address>
			</div>
			<div class="footer-col">
				<h3 class="subscribe-header">S'abonner</h3>
				<p>
					Pour être tenus informés de nos activités (articles, publications, retraites), rejoignez notre liste de diffusion.
				</p>
				<%= form_for(Subscriber.new) do |f| %>
					<%= f.label "Email:" %>
					<%= f.text_field :email %>
					<%= f.hidden_field :language, :value => "French" %>
					<%= f.submit "S'abonner", class: "button" %>
				<% end %>
			</div>
			<div class="footer-col footer-col-paragraph">
				<h3 class="follow-header">Échanger</h3>
				<p>Rejoignez la communauté Facebook d'Essence Diamant France:</p>
				<a href="https://facebook.com/EssenceDiamantFrance" target="_blank"><%= image_tag image_path('facebook-link.gif')%></a>
			</div>
		</div>
		<div id="copy">
	    <p>
		    Créé avec Ruby on Rails par 
		    <a href="http://joepeloquin.com/" target="_blank">Joe Peloquin</a> 
		    • Textes: Kevin Dancelme •
      </p>
      <p>
  	    © 2013 APPROCHE DIAMANT (DIAMOND APPROACH), RIDHWAN et le symbole "Hu" sont des marques déposées de la Fondation Ridhwan.
      </p>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header id="navbar">
  <div id="navbar-inner">
  	<%= image_tag image_path('hu_small_transparent.png'), id: "logo-image" %>
    <%= link_to "Essence Diamant France", root_path, id: "logo" %>
		<nav class="nav">
		  <ul>
		  	<!--
				<li class="strength">
					<%= link_to "Accueil", root_path %>
				</li>
				-->
				<li class="clarity dropdown">
					<%= link_to "Textes et Articles", '#' %>
					<div class="dropdown-box">
						<ul>
							<li><%= link_to "L'Approche Diamant", lapproche_diamant_path %></li>
							<li><%= link_to "Hameed L'Enseignant", hameed_lenseignant_path %></li>
							<li><%= link_to "La Collecte du Miel", la_collecte_du_miel_path %></li>
						</ul>
					</div>
				</li>
				<!--
				<li class="will">
					<%= link_to "Nous Soutenir", '#' %>
				</li>
				<li class="compassion">
					<%= link_to "Communauté", '#' %>
				</li>
				<li class="clarity">
					<%= link_to "Contact", '#' %>
				</li>
				-->
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/_quotebox.html.erb
<div id="quote-box">
  <p class="quote">
  	<em><%= quote(yield(:quote)) %></em>
  </p>
  <p class="author">
  	<strong>A.H. Almaas, <em>Essence</em></strong>
  </p>
</div>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all", 
  	  																				"data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %> 
  </head>
  <body>
	  <%= render 'layouts/header' %>
	   <div id="main-wrapper">
        <%= render 'layouts/quotebox' %>
        <%= yield %>
      </div>
    
    <%= render footer(yield(:footer)) %>
    <!--<%= debug(params) if Rails.env.development? %>-->
  </body>
</html>

app/views/static_pages/_announcementbox.html.erb
<div id="announcement-box">
  <h2>Actualités</h2>
  <ul>
    <li>
      <h4>Bienvenue!</h4>
      <span>
        Notre site internet est en cours de développement. N'hésitez pas à 
        <a href ="mailto:essencediamant@gmail.com" target="_blank"> nous contacter </a>
        pour nous signaler toute amélioration potentielle.
      </span>
      <span>
        Pour être tenu informé des actualités du site (publications, articles, évènements) n’hésitez pas à rejoindre notre
        <%= link_to " liste de diffusion.", root_path(:anchor => "bottom") %>
      </span>
    </li>
  </ul>
</div>

app/views/static_pages/english.html.erb
<% provide(:quote, '"The vague, metaphoric, or poetic ways of describing the process of rebirth often add more confusion than clarification. They are aesthetically appealing and often powerfully inspiring, but for a person who is thirsting - even dying - a beautiful way of describing the road that leads to the well is not as important as a clear, precise and succint way. Also, the precision has an aesthetic of its own, a clear and luminous beauty like the beauty of a precious diamond."') %>
<% provide(:footer, 'layouts/englishfooter') %>
<div id="main">
	<section>
		<p>
			<strong>Welcome to the Essence Diamant France website!</strong>
		</p>		
		<p>
			We are a non-profit organization gathering students of the Diamond Approach and people interested in supporting the development of this teaching in the French language.
		</p>
		<p>
			This project stemmed from the wish to share this precious and life-changing teaching with our communities, our friends and family, who could not read the teachings in English or join existing groups in other countries. We thought it was time to give the francophone world access to the writings and prepare the ground for groups in France and French-speaking countries. It also made sense to those of us living in France to plant seeds for a Diamond Approach group based in France, as our sense is that it might become more difficult for teachers and students to travel long distances in the future, given the rapid planetary changes around climate and energy resources.
		</p>
		<p>
			Our three main objectives are :
			<ol>
          <li> 
          	<p>
        	    Translating and publishing books, through our publishing house, Adab Éditions. We would like to propose books of quality and a beautiful collection, as well as ebooks. Any profits generated from the sales of the first round of books will fund future translations and publications.
						</p>
          </li>
          <li>  
          	<p>
        	  	Organizing workshops for Ridhwan teachers to present the Diamond Approach in France.
        		</p>
          </li>
          <li>
          	<p> 
        	  	Creating and maintaining this website, with texts in French, links and information about the Diamond Approach, as a first contact for those interested in the teachings. The website will provide the possibility of ordering books and ebooks online once they are available.
        	  </p> 
          </li>
        </ol>
		</p>
    <p>
			All of our actions - website, publications and organization of events – are funded by donations. If you would like to support our actions, please contact us. There will soon be an opportunity to make donations on this site.
		</p>
		<p>
			<small>
				Note: Although we are primarily based in France at the moment, we would like to invite and support people from other French-speaking areas (Belgium, Switzerland, Québec, …) interested in supporting the Diamond Approach in their community. 
			</small>
		</p>
		<p>
			<small>
				<em>
					Back to 
					<%= link_to " French Home Page", root_path %>
				</em>
			</small>
		</p>
	</section>
</div>

app/views/static_pages/home.html.erb
<div id="main"> 
<%= render 'static_pages/announcementbox' %>
  <section>
    <p>
      <small>
        <em>
            For english speaking visitors, you are invited to view our
            <%= link_to " English Home Page.", english_path %>
        </em>
      </small>
    </p>
    <p>
      <strong>Essence Diamant France</strong> est une association à but non-lucratif, qui rassemble des étudiants de l’Approche Diamant et des personnes intéressées par l’Approche Diamant. Elle a pour mission de rendre accessible en français cet enseignement, au moyen de trois activités principales : 
        <ol>
          <li> 
        	  <p>la traduction et la publication de livres et de textes concernant l’Approche Diamant ;</p>
          </li>
          <li>  
        	  <p>l’organisation de journées de pratique et de retraites de l’Approche Diamant en France ;</p>
          </li>
          <li> 
            <p>le développement de ce site internet, voulu comme un portail francophone sur l’Approche Diamant.</p>
          </li>
        </ol>
    </p>
    <p>
      Si vous voulez être tenus informés de nos activités et de l’actualité du site, vous pouvez vous inscrire à notre
      <%= link_to " liste de diffusion.", root_path(:anchor => "bottom") %>
    </p>
    <p>
      Pour nous contacter : <a href ="mailto:essencediamant@gmail.com" target="_blank">essencediamant@gmail.com</a>
    </p>
  </section>
  <div class="section-separator"></div>
  <section>
    <h3>Qu’est-ce que l’Approche Diamant ?</h3>
    <p>
  	  L’approche diamant est une voie spirituelle contemporaine, développée par A.H. Almaas. Elle s’ancre dans une compréhension précise à la fois du développement psychologique de l’individu et des aspects spirituels de sa nature essentielle. C’est à dire que cette approche prend en considération la totalité de l’être, dans ses réalités physiques, psychologiques et spirituelles, ce qui lui permet notamment de reconnaître les corrélations entre structures de la personnalité et aspects essentiels. Ainsi, l’ego et les structures de la personnalité, avec lesquels nous sommes le plus souvent identifiés, ne sont plus seulement rejetées ou abordées comme des obstructions à une existence vraie et réalisée, mais ils sont vus comme des reflets de notre vraie nature qui peuvent nous aider à reprendre contact avec elle. Du point de vue de ce logos, ce ne sont pas simplement des barrières ; ce sont également des accès.
    </p>
    <p>
      L’Approche Diamant reconnaît l’unicité de chaque individu, et s’adapte aux besoins uniques de chaque personne à chaque instant, en l’aidant à identifier les étape successives naturelles à son développement particulier. 
    </p>
    <p>
      Elle utilise pour cela une méthodologie spécifique qui inclut des enseignements de groupe, des méditations et des exercices. La pratique centrale de ce travail dynamique de déploiement de l’âme est l’investigation ouverte de l’expérience personnelle (open inquiry). 
    </p>
  </section>
  <section>
    <h3>L’investigation ouverte</h3>
    <p>
  	  L’investigation encourage et active l’exploration ouverte de notre expérience immédiate, sans préconceptions ni préjugés quant au résultat de cette exploration. 
    </p>
    <p>
      Le point de départ de cette exploration peut être n’importe quelle expérience. L’investigation continue en tenant compte et en intégrant tout ce qui se présente : les perceptions, les souvenirs, les réalisations et les prises de conscience, les émotions, les sensations corporelles, l’intuition et les manifestations d’énergies subtiles telles que le chi. Progressivement et naturellement, le processus de l’investigation ouverte révèle les obstacles inconscients à la réalisation de soi, lesquels sont uniques pour chaque étudiant. 
    </p>
    <p>
      À mesure que cette exploration se poursuit d’une expérience à une autre, notre conscience s’ouvre à des niveaux d’expérience de plus en plus profonds, pour finalement s’ouvrir à l’Essence ; des dimensions plus profondes de l’Essence sont révélées et intégrées. L’investigation, ainsi, ouvre vers une expansion, une guérison, une libération et un épanouissement. Sa conséquence ultime est une liberté authentique, et l’expérience de notre vraie nature et de notre potentiel humain complet à travers toutes ses manifestations.
    </p>
  </section>
  <section>
    <h3>A.H. Almaas</h3>
    <p>
      A.H. Almaas est le nom de plume de A. Hameed Ali. Hameed Ali est né au Koweït en 1944. À l’âge de 18 ans, il immigra aux États-Unis pour y poursuivre des études de physique à l’université de Berkeley, en Californie. Durant son travail de doctorat, il atteignit un tournant critique dans sa vie qui l’amena à questionner de plus en plus profondément les aspects psychologiques et spirituels de la nature humaine. Son intérêt pour la vérité de la nature humaine et la nature réelle de la réalité mena à la création et à l’émergence de l’Approche Diamant.
    </p>
    <p>
      Pour plus d’informations (en anglais): 
      <a href="http://ahalmaas.com/" target="_blank">www.ahalmaas.com</a>
    </p>
  </section>
  <section>
    <h3>L’école Ridhwan</h3>
    <p>
  	  L’Approche Diamant est enseignée au sein de l’école Ridhwan, constituée par les différents groupes de pratique qui se sont formés depuis 1977. 
    </p>
    <p>
		  Lien vers la carte des groupes de pratique en Europe : 
      <a href="http://ridhwan.org/school/locations/europe/" target="_blank">www.ridhwan.org/school/locations/europe/</a> 
    </p>
    <p>
      La Fondation Ridhwan est l’organisation à but non-lucratif mise en place pour soutenir et préserver l’intégrité des enseignements de l’Approche Diamant. 
    </p>
    <p>
      Pour accéder au site officiel de l’école Ridhwan (en anglais) :
      <a href="http://ridhwan.org" target="_blank">www.ridhwan.org</a> 
    </p>  
  </section>
</div>
<a id="bottom"></a>

app/views/static_pages/texts_3_la_collecte_du_miel.html.erb
<div id="main">
	<section>
		<div class="title">
			<h2>La Collecte du Miel</h2>
		</div>
		<p>
			Il existait, et peut-être existe-t-il toujours, une école secrète en Afghanistan où durant des milliers d’années s’est pratiqué le Travail ; cette école portait le nom de « Sarmoun Darq », ce qui signifie « la Ruche », ou encore « les Collecteurs de Miel ». Le travail de cette ruche consistait à collecter la connaissance humaine durant les périodes où celle-ci était disséminée, et à la conserver pour les temps futurs où elle pourrait à nouveau être utilisée. Pratiquée principalement durant les périodes difficiles sur Terre, les périodes de troubles ou de guerre, cette activité est si profonde que la plupart des gens ne peuvent même pas concevoir sa portée ni sa signification.
		</p>
		<p>
			Lorsque nous disons que les Sarmoun Darq collectent la connaissance humaine, nous ne parlons pas d’information. L’information peut être collectée dans des livres. Il n’est pas nécessaire de créer une école ou une société secrète pour collecter des informations. La connaissance dont nous parlons est, elle, matérielle, de la même façon que le miel est matériel. La connaissance est collectée de la même manière que les abeilles collectent le nectar des fleurs et le transforment en miel. C’est pourquoi on appelle cette école « la Ruche » ; sa fonction est de collecter toutes sortes de nectars – les aspects de la connaissance essentielle. Les membres de cette école ont la capacité de concentrer et de transformer ces nectars précieux et aromatiques en un miel épais et doux qu’il est alors possible de conserver dans des flasques spéciales. Lorsque le temps est venu, les flasques sont ouvertes et la connaissance est offerte en fonction des besoins.
		</p>
		<p>
			Les nectars sont les différents aspects de la connaissance de l’Essence, et le miel est la connaissance pure, distillée de l’Essence. L’image des abeilles, du miel, de la ruche et du nectar est la description la plus proche de ce qu’est en réalité cette école. C’en est la description la plus proche car la connaissance de l’Essence est une substance qui peut être collectée, concentrée et distillée. Cela devient évident lorsque nous comprenons que l’Essence existe de la même manière que le miel existe, ou que les nectars existent. La vraie connaissance de l’Essence est l’Essence elle-même. L’Essence est cette connaissance.
		</p>
		<p>
			Cette école, Sarmoun Darq, collecte l’Essence humaine durant les périodes de crise sur Terre, et la préserve dans des flasques particulières. Ces flasques spéciales sont des êtres humains soigneusement préparés. De cette façon, la connaissance est préservée et transmise de flasque en flasque jusqu’à ce que l’on ait besoin d’elle. Alors ces flasques,  ces récipients humains, sont envoyés dans différents endroits pour délivrer une connaissance spécifique, une substance à la densité et à la profondeur particulières, adaptées aux capacités d’absorption de leur destinataires.
		</p>
		<p>
			Si l’on observe n’importe quel système, groupe ou école de Travail, de la façon la plus profonde, la plus directe, la plus évidente, la plus phénoménologique, alors on constate que le travail qui s’y fait est simplement la collecte, la distillation et la purification de l’Essence humaine, de façon à la rendre aussi concentrée que possible chez un être humain. Cela est réalisé par la pratique des techniques et des méthodes dont le groupe dispose à un instant donné. Tout comme les abeilles transforment le pollen en miel, les membres collectent les nectars et les transforment en Essence humaine, pour eux-mêmes et pour tous les autres. L’activité particulière dépend de la personne en charge de l’école qui prescrit la méthode à suivre, chacun selon sa capacité propre. Souvent, la plupart des individus ne savent même pas ce qu’il sont en train de faire. Il sont seulement conscients de l’activité elle-même ; ils ne savent pas tout ce que celle-ci peut accomplir. En temps voulu, comme nous l’avons observé dans le travail que nous faisons ici, les gens comprennent de plus en plus ce qu’il sont réellement en train de faire.
		</p>
		<p>
			Au début, ce que nous voyons est le travail autour de nos émotions. Nous ressentons, nous regardons, nous écoutons, en observant nos réactions, en prenant conscience de nos schémas internes. Au bout d’un certain temps, nous commençons à voir les connexions entre ces émotions et la perte de divers aspects de notre essence. Et plus nous ressentons cette perte, plus l’Essence est présente en nous.
		</p>
		<p>
			Dans le travail que nous faisons ici, chacun travaille individuellement la plupart du temps, que cela soit durant les sessions individuelles ou les contextes de groupe.  Chacun fait sa part, chacun collecte ce qu’il peut de nectar, nectar dont la qualité et la densité varient en fonction de ses capacités. Il est alors nécessaire pour tout le monde de se rassembler et de pratiquer une certaine activité qui, au niveau le plus profond, est la collecte de ces nectars en un endroit unique, de façon à ce que, selon un procédé particulier, le nectar puisse être purifié et distillé, rendu aussi concentré que possible. C’est ce que l’on fait durant le travail du week-end. Plus précisément, c’est la fonction de la période de travail du dimanche après-midi. Ce n’est pas simplement la fin du week-end ; c’est un moment durant lequel tout le travail effectué depuis notre dernière rencontre est présent en un endroit. Son intensité s’est développée durant le week-end, et chacun a fait sa part. Alors nous nous rassemblons de façon à ce que ce nous avons collecté puisse cristalliser. L’Essence est alors présente d’une façon bien plus palpable, bien plus définie. Chaque week-end apporte une qualité différente. Et chaque aspect de l’Essence devient plus clair, plus palpable, plus pur, plus concentré. Ainsi, chacun peut y gouter.
		</p>
		<p>
			C’est le niveau le plus profond du travail. L’activité particulière que nous pratiquons ici les dimanches après-midi est l’activité d’être pleinement présent, aussi présent que possible, tout en pratiquant des activités physiques telles que jardiner, peindre, etc. Nous ressentons, nous regardons, nous écoutons avec les qualités essentielles présentes à cet instant, tout en accomplissant la tâche ou l’activité dans laquelle nous sommes impliqués. Cette activité remplit à la fois la fonction que je viens de décrire, et nous permet également de pratiquer l’acte d’être pleinement présent dans une atmosphère et dans un environnement où cela est encouragé. La présence de nombreuses personnes engagées dans la même activité ajoute de l’énergie. Cette énergie n’est pas simplement additive. La présence de l’Essence est contagieuse, et comme tout le monde ressent, regarde et écoute intensément tout en vaquant à ses activités, il devient possible de créer une certaine quantité de miel sous une forme plus concentrée qu’il n’est possible en d’autres circonstances. Ressentir, regarder, écouter donne donc à chaque personne une capacité nouvelle de présence et permet à chacun de gouter le miel. Chacun d’entre nous peut alors prendre cette expérience de l’Essence et cette capacité de présence et les appliquer dans notre vie. Progressivement, il devient possible d’intégrer de plus en plus ces capacités dans notre vie de telle sorte que celle-ci devient de plus en plus la vie essentielle.
		</p>
		<p>
			Ces méthodes sont scientifiques. Lorsque vous les suivez, vous arrivez à des résultats précis. Si vous ne les suivez pas, il se passe quelque chose d’autre. Il est beaucoup plus facile pour une multitude d’abeilles de produire du miel que pour une abeille seule. Une abeille isolée ne produira pas de miel. Elle dépérira très rapidement. Vous ne verrez jamais une abeille seule avec sa propre ruche en train de faire du miel. Cet exemple de l’ancienne école de Sarmoun Darq illustre le type de travail que nous faisons ici.
		</p>
	</section>
	<div class="footnote">
		<span>Extrait de Diamond Heart, Book One : Elements of the Real in Man</span>
		<span>Shambhala, 1987</span>
		<span>Traduction : Kevin Dancelme</span>
	</div>
</div>

app/views/subscribers/english_subscribe_failure.html.erb
<% provide(:quote, '"The vague, metaphoric, or poetic ways of describing the process of rebirth often add more confusion than clarification. They are aesthetically appealing and often powerfully inspiring, but for a person who is thirsting - even dying - a beautiful way of describing the road that leads to the well is not as important as a clear, precise and succint way. Also, the precision has an aesthetic of its own, a clear and luminous beauty like the beauty of a precious diamond."') %>
<% provide(:footer, 'layouts/englishfooter') %>
<div id="main">
	<section>
		<h3>Sorry...</h3>
		<p>
			Your attempt to subscribe was unsuccessful. Your email address may have been entered incorrectly or you may already be subscribed.
		</p>
  </section>
</div>

app/views/subscribers/english_subscribe_success.html.erb
<% provide(:quote, '"The vague, metaphoric, or poetic ways of describing the process of rebirth often add more confusion than clarification. They are aesthetically appealing and often powerfully inspiring, but for a person who is thirsting - even dying - a beautiful way of describing the road that leads to the well is not as important as a clear, precise and succint way. Also, the precision has an aesthetic of its own, a clear and luminous beauty like the beauty of a precious diamond."') %>
<% provide(:footer, 'layouts/englishfooter') %>
<div id="main">
	<section>
		<h3>Thank you for subscribing.</h3>
		<p>
			We will send you updates as we continue to work towards our goal of bringing the Diamond Approach to France.
		</p>
  </section>
</div>

app/views/subscribers/french_subscribe_failure.html.erb
<div id="main">
	<section>
		<h3>Désolé...</h3>
		<p>
			Votre tentative d'inscription a échoué. Il se peut que vous ayez entré un adresse email incorrecte, ou que vous soyez déjà inscrit à notre liste.
		</p>
  </section>
</div>

app/views/subscribers/french_subscribe_success.html.erb
<div id="main">
	<section>
		<h3>Merci.</h3>
		<p>
			Votre adresse a bien été ajoutée à notre liste d'information. Nous vous informerons dès que des nouvelles ressources sur l'Approche Diamant seront accessibles en français.
		</p>
  </section>
</div>